# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
# Preparations
fresh = Preparation.create(
  :name => 'fresh',
  :recipe => 'This is a special herb that requires use when fresh. Drying this herb will result in essential healing properties being lost. Ensure making a fresh preparation (fresh herb infusion, fresh herb tincture, fresh herb honey...) as opposed to using dried herb, and specifically do not dry collections or purchase dried herb.'
)
infusion = Preparation.create(
  :name => 'infusion',
  :recipe => 'Also known as a nice cup of tea, tisane, or ceremonial cup. This preparation is great for immediacy of readiness, and is also great for those herbs that get very bitter. Chamomile, for example, is a lovely infusion. The shorter steeping time of the infusion can help those who prefer to avoid access to her more bitter properties.\n\nTo prepare an infusion, use a teaspoon to a tablespoon of dried herb per cup of water. The water should have just stopped boiling, and then pour directly on the herbs, preferably loose and able to mingle in the infusion container (a jar or pyrex measuring pitcher will do the job well). Let steep covered as long as you can wait, perhaps 15 minutes, then strain cup by cup.\n\nThis preparation is best used for \'soft parts\' such as leaves and flowers, although there are \'hard parts\' that sometimes readily give their constituents nicely to an infusion such as elderberries. Hawthorn berries are notorious for not enjoying an infusion.'
)
decoction = Preparation.create(
  :name => 'decoction',
  :recipe => 'This is a lovely way to somewhat quickly prepare a tea composed of \'hard parts\' such as bark, berries, roots or twigs.\n\nTo prepare a decoction, use a teaspoon to a tablespoon of dried herb per 2 cups of water. Bring water to a boil, then turn the heat down as low as possible. The water should barely be bubbling at a small simmer. You may be able to move your pot partially off the burner if lowest heat is too hot. Add your herbs, and allow to decoct for 20-30 minutes. The water may be at about half it\'s original volume, but no less.'
)
overnight_infusion = Preparation.create(
  :name => 'overnight_infusion',
  :recipe => 'Overnight infusions are a great way to drink herbs. Because of the long steeping process, highly nutritious herbs can give more of their vitamins and minerals. Both \'hard parts\' (bark, berries, roots or twigs) and soft parts (leaves and flowers) enjoy this preparation.\n\nTo prepare an overnight infusion, use a teaspoon to a tablespoon of dried herb per cup of water. The water should have just stopped boiling, and then pour directly on the herbs, preferably loose and able to mingle in the infusion container (a jar or pyrex measuring pitcher will do the job well). Let steep covered overnight or about 8 hours.\n\nAn overnight infusion is prepared in the same way as an infusion with the exception of a much longer steep time. It is said that this preparation can be ready as soon as 4 hours after start of the steep, but the general guideline of 8 hours is preferred.'
)
tincture = Preparation.create(
  :name => 'tincture',
  :recipe => 'Tinctures are surprisingly easy to prepare, but do take a bit of time. The preparation lends itself to making fairly direct medicine out of herbs. In addition to your chosen herb, you will need a tight sealing jar, and your choice of alcohol. Alcohol can be any high proof drinking alcohol such as vodka, whiskey, or whatever you prefer.\n\nTo prepare a tincture, decide how much volume of tincture you would like in your jar. Mark the jar at this point. If you are making a tincture out of soft parts (leaves or flowers), imagine dividing this volume into 3, and mark the lower third. If you are making a tincture out of hard parts (bark, berries, roots or twigs), imagine dividing this volume into 4, and mark the lower quarter. If you are using fresh herb, gently put fresh herb all the way up to your tincture volume mark, and just cover with your alcohol. If you are using dried herb, fill the jar to the lower mark with herb, and then up to the tincture volume mark with alcohol. Tightly cover your tincture, and gently turn a few times to mix the herb. Place in a cool place out of direct sunlight where the tincture can get your attention, and gently turn a few times a day, then a week. Allow the tincture to steep for about a month, then strain as needed or strain into a new vessel. Be sure and label each tincture vessel! This preparation will generally last more than 5 years.\n\nSome tinctures that are great to always keep on hand are Thyme (for fighting colds and flus), Meadowsweet (great for all kinds of gastrointestinal distress), Turmeric (an amazing anti-inflammatory, but caution, she stains quickly), and Motherwort (an amazing woman\'s herb).'
)
glyceride = Preparation.create(
  :name => 'glyceride',
  :recipe => 'Glycerides are technically a tincture with a different menstrum, or tincturing liquid. They taste very sweet and often are less serious and medicinal than alcohol tinctures. Instead of using alcohol, the glyceride tincture uses glycerol. This glycerol will need to be diluted, but at a different rate for fresh versus dried herb. In addition to your chosen herb, you will need glycerol, a tight sealing jar and possibly some plastic wrap to place between the glass and the lid if you notice any corrosion in the lid during the steep.\n\nTo prepare a fresh herb glyceride, decide how much volume of tincture you would like in your jar. Mark the jar at this point. Gently put fresh herb all the way up to your mark. Fill the jar about 90% with glycerol, and then add water to the mark. Tightly cover your glyceride, and gently turn a few times to mix the herb. Place in a cool place out of direct sunlight where the glyceride can get your attention, and gently turn a few times a day, then a week. Allow the glyceride to steep for about a month, then strain as needed or strain into a new vessel. Be sure and label each glyceride vessel! This preparation will generally last 3-5 years.\n\nGlycerides are a great alternative to alcohol tinctures for those who cannot use alcohol, and some herbs seem to prefer glycerol as a menstrum. Some glycerides that are great to always keep on hand are Lemon Balm (for fighting cold sores and seasonal affective disorder) and Rose (great to add to alcohol tincture that are bitter, bringing love and lightness).'
)
honegar = Preparation.create(
  :name => 'honegar',
  :recipe => 'Honegars are technically a tincture with a different menstrum, or tincturing liquid, that also has honey added after the tincturing process. Instead of using alcohol, the honegar tincture uses vinegar. In addition to your chosen herb, you will need apple cider vinegar, raw honey (or try using an infused honey, another herbal preparation), a tight sealing jar and possibly some plastic wrap to place between the glass and the lid if you notice any corrosion in the lid during the steep.\n\nTo prepare a honegar, decide how much volume you would like in your jar. Mark the jar at this point. If you are making a honegar out of soft parts (leaves or flowers), imagine dividing this volume into 3, and mark the lower third. If you are making a honegar out of hard parts (bark, berries, roots or twigs), imagine dividing this volume into 4, and mark the lower quarter. If you are using fresh herb, gently put fresh herb all the way up to your volume mark, and just cover with apple cider vinegar. If you are using dried herb, fill the jar to the lower mark with herb, and then up to the volume mark with apple cider vinegar. Tightly cover your preparation, and gently turn a few times to mix the herb. Place in a cool place out of direct sunlight where the preparation can get your attention, and gently turn a few times a day, then a week. Allow to steep for about a month, then strain into a larger new vessel. Add honey to taste, 1/4 to 1/3 of the resultant vinegar volume is good amount. Gently turn to mix. Be sure and label each tincture vessel! This preparation will generally last 1-2 years.\n\nSome tinctures that are great to always keep on hand are Thyme (for fighting colds and flus), Meadowsweet (great for all kinds of gastrointestinal distress), Turmeric (an amazing anti-inflammatory, but caution, she stains quickly), and Motherwort (an amazing woman\'s herb).'
)
infused_oil = Preparation.create(
  :name => 'infused_oil',
  :recipe => 'Infused oils can be great in cooking or in body care. You can choose from many oils, although quality olive oil is recommended unless the fragrance would interfere with the intention. It is much more difficult to prepare a fresh herb infused oil than a dried herb infused oil... it is much recommended to dry any fresh herb to prepare it for an oil infusion. If this removes desired properties from the herb (such as in the case of Dandylion flowers or licorice flavored long leafy herb), a fresh herb sunny steep oil infusion recipe is reluctantly included. Fresh herb oil infusions spoil easily during a sunny steep, however a double boiler oil infusion might be a good compromise.\n\nTo prepare a dried herb oil infusion, decide how much volume you would like in your jar, and mark the jar at this point. If you are making an infused oil out of soft parts (leaves or flowers), imagine dividing this volume into 3, and mark the lower third. If you are making an infused oil out of hard parts (bark, berries, roots or twigs), imagine dividing this volume into 4, and mark the lower quarter. If you are using fresh herb, gently put fresh herb all the way up to your volume mark, and just cover with oil. At this point you can either choose a sunny steep which takes a month, or a double boiler steep which is generally ready in a day or so. For a dried herb sunny steep, cover the jar, gently turn to mix the herbs, and place in a very sunny window. For a fresh herb sunny steep (not recommended), cover jar with a clean cloth and secure with a rubber band. For a fresh or dried double boiler steep, place the jar in a saucepan and add water to the saucepan until the jar oil level is cleared from the outside. Remove the jar, bring the water to a boil and turn off. Once the water calms, gently place the jar into the oil. When the water is lukewarm, remove the jar, bring the water to a boil and turn off. Once again, return the jar to the hot water, and allow to steep again. Repeat this cycle 5-10 times with soft parts, or 10-15 times with hard parts. At the end of fresh, dried, sunny or double boiler steep, ensure the oil is tightly covered with a lid. If you think there might be residual water from a fresh herb infused oil, take the strained resultant oil, heat up a pot of water as described for the double boiler steep, and place uncovered jar into water. This can allow water to be more rapidly evaporated out of the oil. Any water in the oil will greatly increase the chance of spoilage... check any fresh infused oil preparations for fuzziness or cloudiness and discard if found.'
)
infused_honey = Preparation.create(
  :name => 'infused_honey',
  :recipe => 'Infused honey is a wonderful way of preserving herbs. There are several herbs who\'s properties or fragrance does not withstand drying, such as violets and dandylions. \n\nTo prepare an infused honey, decide how much volume of honey you would like in your jar. Mark the jar at this point. If you are making an infused honey out of soft parts (leaves or flowers), imagine dividing this volume into 3, and mark the lower third. If you are making an infused honey out of hard parts (bark, berries, roots or twigs), imagine dividing this volume into 4, and mark the lower quarter. If you are using fresh herb, gently put fresh herb all the way up to your volume mark, and just cover with your honey. If you are using dried herb, fill the jar to the lower mark with herb, and then up to the total volume mark with honey. Tightly cover your honey, and gently turn a few times to mix the herb. Place in a sunny window and turn periodically. Allow the honey to steep for about a month. At this point, straining is fairly optional. If your herb is not very edible at this point (still hard, like rosehips as opposed to rose petals), feel free to strain out the herb and pour hot water on it to make a honey tea with the dregs. Otherwise, the herb can be consumed with the honey. If it is difficult to strain the herb out, place the jar in a saucepan, add water to the saucepan to the level of the honey, remove the jar and heat the water to boiling, turn off, and add the jar when the water calms. Strain when the honey is melted and flowing more generously. Be sure and label each tincture vessel! This preparation will generally last more than 5 years.\n\nSome tinctures that are great to always keep on hand are Thyme (for fighting colds and flus), Meadowsweet (great for all kinds of gastrointestinal distress), Turmeric (an amazing anti-inflammatory, but caution, she stains quickly), and Motherwort (an amazing woman\'s herb).'
)
syrup = Preparation.create(
  :name => 'syrup',
  :recipe => 'A syrup is essentially a decoction with honey or honey and whiskey added to extend the shelf life. Syrups should definitely be stored in the refrigerator and can generally last one season (a few weeks to months).\n\nTo prepare a syrup, use 1-2 tablespoon of dried herb per 2 cups of water. Bring water to a boil, then turn the heat down as low as possible. The water should barely be bubbling at a small simmer. You may be able to move your pot partially off the burner if lowest heat is too hot. Add your herbs, and allow to decoct for 20-30 minutes. The water may be at about half it\'s original volume. Strain and allow decoction to cool to a point where you can hold the pot (not by the handle, but by the walls of the pot) comfortably with bare hands. Add half the resultant decoction volume in honey or honey and whiskey and refrigerate.'
)
compress = Preparation.create(
  :name => 'compress',
  :recipe => 'Compresses are external applications of strong teas. Essentially, you make a strong tea (infusion, decoction or overnight infusion as applicable to time constraints and herb type), strain it, soak a clean cloth in the strained tea, and apply it externally to a specific area.'
)
poultice = Preparation.create(
  :name => 'poultice',
  :recipe => 'A poultice is a fresh crushed herb applied externally, or dried herb just covered with boiling water and allowed to cool, then applied externally.\n\n\To prepare a poultice from dried herbs, place amount of herbs to cover affected area in a small bowl. There should be room above to herbs in the bowl. Bring water to a boil and just cover the herbs with the water, then cover the bowl with a lid or small plate. When the herbs are cool enough to apply, place herbs directly on affected area.\n\nTo prepare a poultice from fresh herbs: crush, pulverize, or masticate herbs. Place herbs directly on affected area.\n\nA favorite fresh poultice is Yarrow for cuts and wounds. Yarrow is anti-septic and styptic (which stops bleeding) and is a great wilderness first aid plant. Pick a few fresh-looking bigger leaves (not the oldest leaves, not the youngest leaves), chew on them until the bitter flavor has just plateaued, and apply to the wound.'
)
essential_oil = Preparation.create(
  :name => 'essential oil',
  :recipe => 'Essential oils are much more complex to make than these other preparations, but are readily available for purchase. They are rarely used neat, and not always safe to use diluted in a carrier oil either. Be sure and read about specific essential oils before using, and always test before using.\n\nGenerally, essential oils are great for making anointing oils at a dilution of 1 drop per 9 drops of carrier oil. Jojoba is a great carrier oil as it does not have a strong odor and is fairly shelf stable. Smelling salts are another great way to use essential oils. Place salt in a small salve jar. Add a few drops of essential oil directly to the salt. When you need a smell-cation, open the jar and inhale.'
)
steam = Preparation.create(
  :name => 'steam',
  :recipe => 'Steams are a bit luxurious. They are great for the skin, and are extremely helpful in helping with head colds and nasal congestion. You will need a large stainless steel bowl, a small and larger bath towl, and your chosen herbs.\n\nTo prepare your steam, place a small towel on a table and the stainless bowl on top. Add a tablespoon or two of desired herbs, and when you are ready, pour just boiling water ofer the herbs about 1/4 to 1/3 up the bowl (a few cups). Sit at the table and cover your head and the bowl with the towel. Adjust the intensity of the steam by lowering or raising your face, or venting the towel a bit. Steam for as long as desired.'
)
bath = Preparation.create(
  :name => 'bath',
  :recipe => 'Some herbs are particulary suited to bathing with, either for relaxing purposes or specifically for skin healh.\n\n\To prepare a bath, begin a strong infusion 30 minutes before the bath or decoction an hour before the bath. In the case of a decoction, turn of the simmer after 30 minutes. draw your bath, and optionally filter your herbs out of the tea as it is added to the hot water. Enjoy!'
)


adaptogen = Property.create(:name => 'adaptogen', :definition => 'helps adapt to stress and different circumstances, climates, time zones...')
adrenal_tonic = Property.create(:name => 'adrenal tonic', :definition => 'supports a healthy stress response and replenish the adrenals')
alterative = Property.create(:name => 'alterative', :definition => 'supports the blood and building healthy blood')
analgesic = Property.create(:name => 'analgesic', :definition => 'pain relief')
anti_bacterial = Property.create(:name => 'anti-bacterial', :definition => 'tends to slow, stunt or stop growth of bacteria')
anti_coagulant = Property.create(:name => 'anti-coagulant', :definition => 'blood thinning')
anti_depressant = Property.create(:name => 'anti-depressant', :definition => 'tends to support happiness')
anti_emetic = Property.create(:name => 'anti-emetic', :definition => 'helps stop feelings of nausea')
anti_fungal = Property.create(:name => 'anti-fungal', :definition => 'tends to slow, stunt or stop growth of fungus')
anti_histamine = Property.create(:name => 'anti-histamine', :definition => '')
anti_inflammatory = Property.create(:name => 'anti-inflammatory', :definition => 'helps reduce inflammation')
anti_microbial = Property.create(:name => 'anti-microbial', :definition => 'tends to slow, stunt or stop growth of bacteria, viruses, fungi and yeasts')
anti_rheumatic = Property.create(:name => 'anti-rheumatic', :definition => '')
anti_septic = Property.create(:name => 'anti-septic', :definition => '')
anti_spasmodic = Property.create(:name => 'anti-spasmodic', :definition => '')
anti_tumor = Property.create(:name => 'anti-tumor', :definition => 'tends to slow, stunt or stop growth of tumor tissue')
anti_viral = Property.create(:name => 'anti-viral', :definition => 'tends to slow, stunt or stop growth of viruses')
antioxidant = Property.create(:name => 'anti-oxidant', :definition => 'tends to slow, stunt or stop oxidation')
aphrodisiac = Property.create(:name => 'aphrodisiac', :definition => 'supports desire')
astringent = Property.create(:name => 'astringent', :definition => 'tightens tissue, tends to dry')
bitter = Property.create(:name => 'bitter', :definition => 'supports digestion')
calming = Property.create(:name => 'calming', :definition => '')
cardiac_tonic = Property.create(:name => 'cardiac tonic', :definition => 'supports heart health')
carminative = Property.create(:name => 'carminative', :definition => 'relieves flatulence often tasty')
cholagogue = Property.create(:name => 'cholagogue', :definition => '')
circulatory_tonic = Property.create(:name => 'circulatory tonic', :definition => 'supports circulation')
demulcent = Property.create(:name => 'demulcent', :definition => 'supports internal juiciness and hydration')
diaphoretic = Property.create(:name => 'diaphoretic', :definition => '')
digestive_tonic = Property.create(:name => 'digestive tonic', :definition => 'supports digestion')
diuretic = Property.create(:name => 'diuretic', :definition => 'helps eliminate water')
emmenagogue = Property.create(:name => 'emmenagogue', :definition => 'helps bring on menses')
emollient = Property.create(:name => 'emollient', :definition => 'supports external juiciness and hydration')
endocrine_tonic = Property.create(:name => 'endocrine tonic', :definition => 'supports the endocrine system')
expectorant = Property.create(:name => 'expectorant', :definition => 'helps remove flem from the lungs')
febrifuge = Property.create(:name => 'febrifuge', :definition => '')
galactagogue = Property.create(:name => 'galactagogue', :definition => 'supports milk production')
hepatic = Property.create(:name => 'hepatic', :definition => 'supports the liver')
hypotensive = Property.create(:name => 'hypotensive', :definition => '')
immune_tonic = Property.create(:name => 'immune tonic', :definition => 'supports the immune system')
kidney_tonic = Property.create(:name => 'kidney tonic', :definition => 'supports the kidneys and elimination')
laxative = Property.create(:name => 'laxative', :definition => 'relieves constipation')
liver_tonic = Property.create(:name => 'liver tonic', :definition => 'supports the liver')
lymphatic_tonic = Property.create(:name => 'lymphatic tonic', :definition => '')
menstrual_regulator = Property.create(:name => 'menstrual regulator', :definition => '')
nervine = Property.create(:name => 'nervine', :definition => 'supports the nervous system, soothes the nerves')
nervine_tonic = Property.create(:name => 'nervine tonic', :definition => 'supports the nervous system, soothes the nerves, useful for daily support')
nourishing_tonic = Property.create(:name => 'nourishing tonic', :definition => '')
nutrient = Property.create(:name => 'nutrient', :definition => '')
nutritive = Property.create(:name => 'nutritive', :definition => '')
nutritive_tonic = Property.create(:name => 'nutritive tonic', :definition => '')
refrigerant = Property.create(:name => 'refrigerant', :definition => 'cooling')
regenerating = Property.create(:name => 'regenerating', :definition => '')
relaxant = Property.create(:name => 'relaxant', :definition => '')
reproductive_tonic = Property.create(:name => 'reproductive tonic', :definition => 'supports reproduction, generally in women')
sedative = Property.create(:name => 'sedative', :definition => '')
tonic = Property.create(:name => 'tonic', :definition => 'generally supportive of body systems, usually good for daily use')
vulnerary = Property.create(:name => 'vulnerary', :definition => 'healing to wounds')

flower = Part.create(:structure => 'flower')
fruit = Part.create(:structure => 'fruit')
leaf = Part.create(:structure => 'leaf')
root = Part.create(:structure => 'root')
whole = Part.create(:structure => 'whole')

blackberry = Plant.create(:common_name => 'blackberry', :species => ['Rubus fructicosus'], :contraindications => [], :image => 'herb_illustrations/blackberry.jpg')
blackberry_leaf = Herb.create(:plant_id => blackberry.id, :part_id => leaf.id, :time_to_collect => 'spring')
HerbalProperty.create(:herb_id => blackberry_leaf.id, :property_id => nutritive.id, :specific => false)
HerbalProperty.create(:herb_id => blackberry_leaf.id, :property_id => tonic.id, :specific => false)
HerbalProperty.create(:herb_id => blackberry_leaf.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => blackberry_leaf.id, :property_id => diuretic.id, :specific => false)
HerbalPreparation.create(:herb_id => blackberry_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
blackberry_root = Herb.create(:plant_id => blackberry.id, :part_id => root.id, :time_to_collect => 'fall')
HerbalProperty.create(:herb_id => blackberry_root.id, :property_id => astringent.id, :specific => false)
HerbalPreparation.create(:herb_id => blackberry_root.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => blackberry_root.id, :preparation_id => decoction.id, :favorite => false)
HerbalPreparation.create(:herb_id => blackberry_root.id, :preparation_id => tincture.id, :favorite => false)
blackberry_fruit = Herb.create(:plant_id => blackberry.id, :part_id => fruit.id, :time_to_collect => 'fall')
HerbalProperty.create(:herb_id => blackberry_fruit.id, :property_id => nutritive.id, :specific => false)
HerbalProperty.create(:herb_id => blackberry_fruit.id, :property_id => tonic.id, :specific => false)
HerbalPreparation.create(:herb_id => blackberry_fruit.id, :preparation_id => honegar.id, :favorite => false)
HerbalPreparation.create(:herb_id => blackberry_fruit.id, :preparation_id => syrup.id, :favorite => false)
HerbalPreparation.create(:herb_id => blackberry_fruit.id, :preparation_id => tincture.id, :favorite => false)
borage = Plant.create(:common_name => 'borage', :species => ['Boragio officinalis'], :contraindications => [], :image => 'herb_illustrations/borage.jpg')
borage_leaf = Herb.create(:plant_id => borage.id, :part_id => leaf.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => borage_leaf.id, :property_id => adrenal_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => borage_leaf.id, :property_id => nervine.id, :specific => false)
HerbalProperty.create(:herb_id => borage_leaf.id, :property_id => adaptogen.id, :specific => false)
HerbalProperty.create(:herb_id => borage_leaf.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => borage_leaf.id, :property_id => anti_rheumatic.id, :specific => false)
HerbalProperty.create(:herb_id => borage_leaf.id, :property_id => febrifuge.id, :specific => false)
HerbalProperty.create(:herb_id => borage_leaf.id, :property_id => galactagogue.id, :specific => false)
HerbalProperty.create(:herb_id => borage_leaf.id, :property_id => emollient.id, :specific => false)
HerbalPreparation.create(:herb_id => borage_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => borage_leaf.id, :preparation_id => tincture.id, :favorite => false)
HerbalPreparation.create(:herb_id => borage_leaf.id, :preparation_id => syrup.id, :favorite => false)
HerbalPreparation.create(:herb_id => borage_leaf.id, :preparation_id => infused_honey.id, :favorite => false)
borage_flower = Herb.create(:plant_id => borage.id, :part_id => flower.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => borage_flower.id, :property_id => adrenal_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => borage_flower.id, :property_id => nervine.id, :specific => false)
HerbalProperty.create(:herb_id => borage_flower.id, :property_id => adaptogen.id, :specific => false)
HerbalProperty.create(:herb_id => borage_flower.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => borage_flower.id, :property_id => anti_rheumatic.id, :specific => false)
HerbalProperty.create(:herb_id => borage_flower.id, :property_id => febrifuge.id, :specific => false)
HerbalProperty.create(:herb_id => borage_flower.id, :property_id => galactagogue.id, :specific => false)
HerbalProperty.create(:herb_id => borage_flower.id, :property_id => emollient.id, :specific => false)
HerbalPreparation.create(:herb_id => borage_flower.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => borage_flower.id, :preparation_id => tincture.id, :favorite => false)
HerbalPreparation.create(:herb_id => borage_flower.id, :preparation_id => syrup.id, :favorite => false)
HerbalPreparation.create(:herb_id => borage_flower.id, :preparation_id => infused_honey.id, :favorite => false)
burdock = Plant.create(:common_name => 'burdock', :species => ['Arctium lappa', 'Arctium minus'], :contraindications => [], :image => 'herb_illustrations/burdock.jpg')
burdock_root = Herb.create(:plant_id => burdock.id, :part_id => root.id, :time_to_collect => 'fall')
HerbalProperty.create(:herb_id => burdock_root.id, :property_id => alterative.id, :specific => false)
HerbalProperty.create(:herb_id => burdock_root.id, :property_id => nourishing_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => burdock_root.id, :property_id => demulcent.id, :specific => false)
HerbalProperty.create(:herb_id => burdock_root.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => burdock_root.id, :property_id => liver_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => burdock_root.id, :property_id => kidney_tonic.id, :specific => false)
HerbalPreparation.create(:herb_id => burdock_root.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => burdock_root.id, :preparation_id => decoction.id, :favorite => false)
HerbalPreparation.create(:herb_id => burdock_root.id, :preparation_id => tincture.id, :favorite => false)
calendula = Plant.create(:common_name => 'calendula', :species => ['Calendula officinalis'], :contraindications => [], :image => 'herb_illustrations/calendula.jpg')
calendula_flower = Herb.create(:plant_id => calendula.id, :part_id => flower.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => calendula_flower.id, :property_id => anti_septic.id, :specific => false)
HerbalProperty.create(:herb_id => calendula_flower.id, :property_id => anti_fungal.id, :specific => false)
HerbalProperty.create(:herb_id => calendula_flower.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => calendula_flower.id, :property_id => anti_microbial.id, :specific => false)
HerbalProperty.create(:herb_id => calendula_flower.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalProperty.create(:herb_id => calendula_flower.id, :property_id => vulnerary.id, :specific => false)
HerbalProperty.create(:herb_id => calendula_flower.id, :property_id => anti_spasmodic.id, :specific => false)
HerbalProperty.create(:herb_id => calendula_flower.id, :property_id => emmenagogue.id, :specific => false)
HerbalPreparation.create(:herb_id => calendula_flower.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => calendula_flower.id, :preparation_id => tincture.id, :favorite => false)
HerbalPreparation.create(:herb_id => calendula_flower.id, :preparation_id => infused_oil.id, :favorite => false)
chamomile = Plant.create(:common_name => 'chamomile', :species => ['Matricaria officinalis'], :contraindications => ['Use caution if allergic to ragweed'], :image => 'herb_illustrations/chamomile.jpg')
chamomile_flower = Herb.create(:plant_id => chamomile.id, :part_id => flower.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => chamomile_flower.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalProperty.create(:herb_id => chamomile_flower.id, :property_id => anti_spasmodic.id, :specific => false)
HerbalProperty.create(:herb_id => chamomile_flower.id, :property_id => nervine.id, :specific => false)
HerbalProperty.create(:herb_id => chamomile_flower.id, :property_id => carminative.id, :specific => false)
HerbalProperty.create(:herb_id => chamomile_flower.id, :property_id => anti_septic.id, :specific => false)
HerbalProperty.create(:herb_id => chamomile_flower.id, :property_id => vulnerary.id, :specific => false)
HerbalProperty.create(:herb_id => chamomile_flower.id, :property_id => anti_microbial.id, :specific => false)
HerbalProperty.create(:herb_id => chamomile_flower.id, :property_id => anti_bacterial.id, :specific => false)
HerbalProperty.create(:herb_id => chamomile_flower.id, :property_id => analgesic.id, :specific => false)
HerbalPreparation.create(:herb_id => chamomile_flower.id, :preparation_id => infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => chamomile_flower.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => chamomile_flower.id, :preparation_id => tincture.id, :favorite => false)
HerbalPreparation.create(:herb_id => chamomile_flower.id, :preparation_id => infused_oil.id, :favorite => false)
HerbalPreparation.create(:herb_id => chamomile_flower.id, :preparation_id => steam.id, :favorite => false)
HerbalPreparation.create(:herb_id => chamomile_flower.id, :preparation_id => poultice.id, :favorite => false)
chickweed = Plant.create(:common_name => 'chickweed', :species => ['Stellaria media'], :contraindications => [], :image => 'herb_illustrations/chickweed.jpg')
chickweed_leaf = Herb.create(:plant_id => chickweed.id, :part_id => leaf.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => anti_rheumatic.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => nutritive_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => demulcent.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => emollient.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => refrigerant.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => vulnerary.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => expectorant.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => lymphatic_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => endocrine_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => chickweed_leaf.id, :property_id => alterative.id, :specific => false)
HerbalPreparation.create(:herb_id => chickweed_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => chickweed_leaf.id, :preparation_id => tincture.id, :favorite => false)
HerbalPreparation.create(:herb_id => chickweed_leaf.id, :preparation_id => honegar.id, :favorite => false)
HerbalPreparation.create(:herb_id => chickweed_leaf.id, :preparation_id => infused_oil.id, :favorite => false)
HerbalPreparation.create(:herb_id => chickweed_leaf.id, :preparation_id => poultice.id, :favorite => false)
dandelion = Plant.create(:common_name => 'dandelion', :species => ['Taraxacum officinale'], :contraindications => [], :image => 'herb_illustrations/dandelion.jpg')
dandelion_leaf = Herb.create(:plant_id => dandelion.id, :part_id => leaf.id, :time_to_collect => 'spring')
HerbalProperty.create(:herb_id => dandelion_leaf.id, :property_id => nutritive.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_leaf.id, :property_id => tonic.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_leaf.id, :property_id => laxative.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_leaf.id, :property_id => cholagogue.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_leaf.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_leaf.id, :property_id => adaptogen.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_leaf.id, :property_id => alterative.id, :specific => false)
HerbalPreparation.create(:herb_id => dandelion_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
dandelion_root = Herb.create(:plant_id => dandelion.id, :part_id => root.id, :time_to_collect => 'fall')
HerbalProperty.create(:herb_id => dandelion_root.id, :property_id => nutritive.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_root.id, :property_id => tonic.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_root.id, :property_id => cholagogue.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_root.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_root.id, :property_id => adaptogen.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_root.id, :property_id => alterative.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_root.id, :property_id => hepatic.id, :specific => false)
HerbalPreparation.create(:herb_id => dandelion_root.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => dandelion_root.id, :preparation_id => decoction.id, :favorite => false)
dandelion_flower = Herb.create(:plant_id => dandelion.id, :part_id => flower.id, :time_to_collect => 'spring')
HerbalProperty.create(:herb_id => dandelion_flower.id, :property_id => nutritive.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_flower.id, :property_id => tonic.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_flower.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => dandelion_flower.id, :property_id => diuretic.id, :specific => false)
HerbalPreparation.create(:herb_id => dandelion_flower.id, :preparation_id => fresh.id, :favorite => false)
HerbalPreparation.create(:herb_id => dandelion_flower.id, :preparation_id => tincture.id, :favorite => false)
elder = Plant.create(:common_name => 'elder', :species => ['Sambuccus nigra'], :contraindications => [], :image => 'herb_illustrations/elder.jpg')
elder_flower = Herb.create(:plant_id => elder.id, :part_id => flower.id, :time_to_collect => 'spring')
HerbalProperty.create(:herb_id => elder_flower.id, :property_id => alterative.id, :specific => false)
HerbalProperty.create(:herb_id => elder_flower.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalProperty.create(:herb_id => elder_flower.id, :property_id => anti_septic.id, :specific => false)
HerbalProperty.create(:herb_id => elder_flower.id, :property_id => vulnerary.id, :specific => false)
HerbalProperty.create(:herb_id => elder_flower.id, :property_id => expectorant.id, :specific => false)
HerbalProperty.create(:herb_id => elder_flower.id, :property_id => diaphoretic.id, :specific => false)
HerbalProperty.create(:herb_id => elder_flower.id, :property_id => febrifuge.id, :specific => false)
HerbalProperty.create(:herb_id => elder_flower.id, :property_id => emollient.id, :specific => false)
HerbalProperty.create(:herb_id => elder_flower.id, :property_id => demulcent.id, :specific => false)
HerbalPreparation.create(:herb_id => elder_flower.id, :preparation_id => infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => elder_flower.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => elder_flower.id, :preparation_id => honegar.id, :favorite => false)
elder_fruit = Herb.create(:plant_id => elder.id, :part_id => fruit.id, :time_to_collect => 'fall')
HerbalProperty.create(:herb_id => elder_fruit.id, :property_id => alterative.id, :specific => false)
HerbalProperty.create(:herb_id => elder_fruit.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => elder_fruit.id, :property_id => laxative.id, :specific => false)
HerbalProperty.create(:herb_id => elder_fruit.id, :property_id => demulcent.id, :specific => false)
HerbalProperty.create(:herb_id => elder_fruit.id, :property_id => immune_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => elder_fruit.id, :property_id => calming.id, :specific => false)
HerbalPreparation.create(:herb_id => elder_fruit.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => elder_fruit.id, :preparation_id => infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => elder_fruit.id, :preparation_id => syrup.id, :favorite => false)
HerbalPreparation.create(:herb_id => elder_fruit.id, :preparation_id => honegar.id, :favorite => false)
HerbalPreparation.create(:herb_id => elder_fruit.id, :preparation_id => infused_honey.id, :favorite => false)
hawthorn = Plant.create(:common_name => 'hawthorn', :species => ['Crataegus succulenta', 'Crataegus erythropoda', 'Crataegus monogyna'], :contraindications => [], :image => 'herb_illustrations/hawthorn.jpg')
hawthorn_fruit = Herb.create(:plant_id => hawthorn.id, :part_id => fruit.id, :time_to_collect => 'fall')
HerbalProperty.create(:herb_id => hawthorn_fruit.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => hawthorn_fruit.id, :property_id => cardiac_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => hawthorn_fruit.id, :property_id => circulatory_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => hawthorn_fruit.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => hawthorn_fruit.id, :property_id => hypotensive.id, :specific => false)
HerbalProperty.create(:herb_id => hawthorn_fruit.id, :property_id => antioxidant.id, :specific => false)
HerbalPreparation.create(:herb_id => hawthorn_fruit.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => hawthorn_fruit.id, :preparation_id => decoction.id, :favorite => false)
HerbalPreparation.create(:herb_id => hawthorn_fruit.id, :preparation_id => infused_honey.id, :favorite => false)
ladys_mantle = Plant.create(:common_name => 'lady\'s mantle', :species => ['Alchemilla vulgaris'], :contraindications => [], :image => 'herb_illustrations/ladys_mantle.jpg')
ladys_mantle_leaf = Herb.create(:plant_id => ladys_mantle.id, :part_id => leaf.id, :time_to_collect => 'spring')
HerbalProperty.create(:herb_id => ladys_mantle_leaf.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => ladys_mantle_leaf.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => ladys_mantle_leaf.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalProperty.create(:herb_id => ladys_mantle_leaf.id, :property_id => emmenagogue.id, :specific => false)
HerbalProperty.create(:herb_id => ladys_mantle_leaf.id, :property_id => vulnerary.id, :specific => false)
HerbalProperty.create(:herb_id => ladys_mantle_leaf.id, :property_id => reproductive_tonic.id, :specific => false)
HerbalPreparation.create(:herb_id => ladys_mantle_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
lemon_balm = Plant.create(:common_name => 'lemon balm', :species => ['Melissa officinalis'], :contraindications => [], :image => 'herb_illustrations/lemon_balm.jpg')
lemon_balm_leaf = Herb.create(:plant_id => lemon_balm.id, :part_id => leaf.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => lemon_balm_leaf.id, :property_id => nervine.id, :specific => false)
HerbalProperty.create(:herb_id => lemon_balm_leaf.id, :property_id => anti_microbial.id, :specific => false)
HerbalProperty.create(:herb_id => lemon_balm_leaf.id, :property_id => anti_viral.id, :specific => false)
HerbalProperty.create(:herb_id => lemon_balm_leaf.id, :property_id => anti_spasmodic.id, :specific => false)
HerbalProperty.create(:herb_id => lemon_balm_leaf.id, :property_id => anti_histamine.id, :specific => false)
HerbalPreparation.create(:herb_id => lemon_balm_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => lemon_balm_leaf.id, :preparation_id => glyceride.id, :favorite => false)
meadowsweet = Plant.create(:common_name => 'meadowsweet', :species => ['Filipendula ulmaria'], :contraindications => [], :image => 'herb_illustrations/meadowsweet.jpg')
meadowsweet_flower = Herb.create(:plant_id => meadowsweet.id, :part_id => flower.id, :time_to_collect => 'spring')
HerbalProperty.create(:herb_id => meadowsweet_flower.id, :property_id => anti_rheumatic.id, :specific => false)
HerbalProperty.create(:herb_id => meadowsweet_flower.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalProperty.create(:herb_id => meadowsweet_flower.id, :property_id => digestive_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => meadowsweet_flower.id, :property_id => anti_emetic.id, :specific => false)
HerbalPreparation.create(:herb_id => meadowsweet_flower.id, :preparation_id => tincture.id, :favorite => false)
mugwort = Plant.create(:common_name => 'mugwort', :species => ['Artemisia vulgaris'], :contraindications => ['CONTRAINDICATED for pregnancy'], :image => 'herb_illustrations/mugwort.png')
mugwort_leaf = Herb.create(:plant_id => mugwort.id, :part_id => leaf.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => mugwort_leaf.id, :property_id => nervine.id, :specific => false)
HerbalProperty.create(:herb_id => mugwort_leaf.id, :property_id => reproductive_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => mugwort_leaf.id, :property_id => emmenagogue.id, :specific => false)
HerbalProperty.create(:herb_id => mugwort_leaf.id, :property_id => carminative.id, :specific => false)
HerbalProperty.create(:herb_id => mugwort_leaf.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalPreparation.create(:herb_id => mugwort_leaf.id, :preparation_id => infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => mugwort_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => mugwort_leaf.id, :preparation_id => tincture.id, :favorite => false)
nettles = Plant.create(:common_name => 'nettles', :species => ['Urtica dioica'], :contraindications => [], :image => 'herb_illustrations/nettles.jpg')
nettles_leaf = Herb.create(:plant_id => nettles.id, :part_id => leaf.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => nettles_leaf.id, :property_id => nutrient.id, :specific => false)
HerbalProperty.create(:herb_id => nettles_leaf.id, :property_id => tonic.id, :specific => false)
HerbalProperty.create(:herb_id => nettles_leaf.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalProperty.create(:herb_id => nettles_leaf.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => nettles_leaf.id, :property_id => alterative.id, :specific => false)
HerbalProperty.create(:herb_id => nettles_leaf.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => nettles_leaf.id, :property_id => anti_viral.id, :specific => false)
HerbalProperty.create(:herb_id => nettles_leaf.id, :property_id => circulatory_tonic.id, :specific => false)
HerbalPreparation.create(:herb_id => nettles_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
oatstraw = Plant.create(:common_name => 'oatstraw', :species => ['Avena sativa'], :contraindications => [], :image => 'herb_illustrations/oatstraw.jpg')
oatstraw_whole = Herb.create(:plant_id => oatstraw.id, :part_id => whole.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => oatstraw_whole.id, :property_id => nervine_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => oatstraw_whole.id, :property_id => nutritive.id, :specific => false)
HerbalProperty.create(:herb_id => oatstraw_whole.id, :property_id => reproductive_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => oatstraw_whole.id, :property_id => anti_depressant.id, :specific => false)
HerbalProperty.create(:herb_id => oatstraw_whole.id, :property_id => demulcent.id, :specific => false)
HerbalProperty.create(:herb_id => oatstraw_whole.id, :property_id => vulnerary.id, :specific => false)
HerbalPreparation.create(:herb_id => oatstraw_whole.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => oatstraw_whole.id, :preparation_id => tincture.id, :favorite => false)
HerbalPreparation.create(:herb_id => oatstraw_whole.id, :preparation_id => bath.id, :favorite => false)
HerbalPreparation.create(:herb_id => oatstraw_whole.id, :preparation_id => compress.id, :favorite => false)
red_clover = Plant.create(:common_name => 'red clover', :species => ['Trifolium pratense'], :contraindications => ['CONTRAINDICATED haemopheliac', 'CONTRAINDICATED long term consistant use (suggested 3 weeks on, 1 week off for long term)'], :image => 'herb_illustrations/red_clover.jpg')
red_clover_flower = Herb.create(:plant_id => red_clover.id, :part_id => flower.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => red_clover_flower.id, :property_id => alterative.id, :specific => false)
HerbalProperty.create(:herb_id => red_clover_flower.id, :property_id => anti_spasmodic.id, :specific => false)
HerbalProperty.create(:herb_id => red_clover_flower.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => red_clover_flower.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalProperty.create(:herb_id => red_clover_flower.id, :property_id => anti_coagulant.id, :specific => false)
HerbalProperty.create(:herb_id => red_clover_flower.id, :property_id => anti_tumor.id, :specific => false)
HerbalProperty.create(:herb_id => red_clover_flower.id, :property_id => nutrient.id, :specific => false)
HerbalPreparation.create(:herb_id => red_clover_flower.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => red_clover_flower.id, :preparation_id => tincture.id, :favorite => false)
red_raspberry = Plant.create(:common_name => 'red raspberry', :species => ['Rubus idaeus', 'Rubus strigosus'], :contraindications => [], :image => 'herb_illustrations/red_raspberry.jpg')
red_raspberry_leaf = Herb.create(:plant_id => red_raspberry.id, :part_id => leaf.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => red_raspberry_leaf.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => red_raspberry_leaf.id, :property_id => tonic.id, :specific => false)
HerbalProperty.create(:herb_id => red_raspberry_leaf.id, :property_id => refrigerant.id, :specific => false)
HerbalProperty.create(:herb_id => red_raspberry_leaf.id, :property_id => emmenagogue.id, :specific => false)
HerbalProperty.create(:herb_id => red_raspberry_leaf.id, :property_id => galactagogue.id, :specific => false)
HerbalPreparation.create(:herb_id => red_raspberry_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => red_raspberry_leaf.id, :preparation_id => tincture.id, :favorite => false)
rose = Plant.create(:common_name => 'rose', :species => ['Rosa spp.'], :contraindications => [], :image => 'herb_illustrations/rose.jpg')
rose_flower = Herb.create(:plant_id => rose.id, :part_id => flower.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => anti_depressant.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => anti_spasmodic.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => aphrodisiac.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => sedative.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => anti_microbial.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => anti_viral.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => anti_septic.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => menstrual_regulator.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => nervine_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => rose_flower.id, :property_id => emollient.id, :specific => false)
HerbalPreparation.create(:herb_id => rose_flower.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => rose_flower.id, :preparation_id => infused_honey.id, :favorite => false)
rose_fruit = Herb.create(:plant_id => rose.id, :part_id => fruit.id, :time_to_collect => 'fall')
HerbalProperty.create(:herb_id => rose_fruit.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => rose_fruit.id, :property_id => tonic.id, :specific => false)
HerbalProperty.create(:herb_id => rose_fruit.id, :property_id => regenerating.id, :specific => false)
HerbalProperty.create(:herb_id => rose_fruit.id, :property_id => anti_bacterial.id, :specific => false)
HerbalPreparation.create(:herb_id => rose_fruit.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => rose_fruit.id, :preparation_id => decoction.id, :favorite => false)
HerbalPreparation.create(:herb_id => rose_fruit.id, :preparation_id => tincture.id, :favorite => false)
HerbalPreparation.create(:herb_id => rose_fruit.id, :preparation_id => syrup.id, :favorite => false)
HerbalPreparation.create(:herb_id => rose_fruit.id, :preparation_id => infused_honey.id, :favorite => false)
thyme = Plant.create(:common_name => 'thyme', :species => ['Thymus vulgaris'], :contraindications => [], :image => 'herb_illustrations/thyme.jpg')
thyme_leaf = Herb.create(:plant_id => thyme.id, :part_id => leaf.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => thyme_leaf.id, :property_id => anti_microbial.id, :specific => false)
HerbalProperty.create(:herb_id => thyme_leaf.id, :property_id => anti_bacterial.id, :specific => false)
HerbalProperty.create(:herb_id => thyme_leaf.id, :property_id => anti_fungal.id, :specific => false)
HerbalProperty.create(:herb_id => thyme_leaf.id, :property_id => anti_septic.id, :specific => false)
HerbalProperty.create(:herb_id => thyme_leaf.id, :property_id => anti_spasmodic.id, :specific => false)
HerbalProperty.create(:herb_id => thyme_leaf.id, :property_id => expectorant.id, :specific => false)
HerbalProperty.create(:herb_id => thyme_leaf.id, :property_id => carminative.id, :specific => false)
HerbalProperty.create(:herb_id => thyme_leaf.id, :property_id => astringent.id, :specific => false)
HerbalPreparation.create(:herb_id => thyme_leaf.id, :preparation_id => tincture.id, :favorite => false)
HerbalPreparation.create(:herb_id => thyme_leaf.id, :preparation_id => overnight_infusion.id, :favorite => false)
vervain = Plant.create(:common_name => 'vervain', :species => ['Verbena hastata'], :contraindications => ['CONTRAINDICATED pregnancy except encouraging contractions'], :image => 'herb_illustrations/vervain.jpg')
vervain_leaf = Herb.create(:plant_id => vervain.id, :part_id => leaf.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => nervine.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => relaxant.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => anti_depressant.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => galactagogue.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => diaphoretic.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => sedative.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => anti_spasmodic.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => hepatic.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => digestive_tonic.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => emmenagogue.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => vulnerary.id, :specific => false)
HerbalProperty.create(:herb_id => vervain_leaf.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalPreparation.create(:herb_id => vervain_leaf.id, :preparation_id => infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => vervain_leaf.id, :preparation_id => tincture.id, :favorite => false)
yarrow = Plant.create(:common_name => 'yarrow', :species => ['Achillea millefolium'], :contraindications => ['CONTRAINDICATED pregnancy'], :image => 'herb_illustrations/yarrow.jpg')
yarrow_flower = Herb.create(:plant_id => yarrow.id, :part_id => flower.id, :time_to_collect => 'summer')
HerbalProperty.create(:herb_id => yarrow_flower.id, :property_id => tonic.id, :specific => false)
HerbalProperty.create(:herb_id => yarrow_flower.id, :property_id => alterative.id, :specific => false)
HerbalProperty.create(:herb_id => yarrow_flower.id, :property_id => diaphoretic.id, :specific => false)
HerbalProperty.create(:herb_id => yarrow_flower.id, :property_id => diuretic.id, :specific => false)
HerbalProperty.create(:herb_id => yarrow_flower.id, :property_id => astringent.id, :specific => false)
HerbalProperty.create(:herb_id => yarrow_flower.id, :property_id => anti_septic.id, :specific => false)
HerbalProperty.create(:herb_id => yarrow_flower.id, :property_id => vulnerary.id, :specific => false)
HerbalProperty.create(:herb_id => yarrow_flower.id, :property_id => anti_inflammatory.id, :specific => false)
HerbalPreparation.create(:herb_id => yarrow_flower.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => yarrow_flower.id, :preparation_id => tincture.id, :favorite => false)
yellow_dock = Plant.create(:common_name => 'yellow dock', :species => ['Rumex crispus'], :contraindications => ['CONTRAINDICATED long term use (suggested 1 week on, 1 week off)'], :image => 'herb_illustrations/yellow_dock.jpg')
yellow_dock_root = Herb.create(:plant_id => yellow_dock.id, :part_id => root.id, :time_to_collect => 'fall')
HerbalProperty.create(:herb_id => yellow_dock_root.id, :property_id => bitter.id, :specific => false)
HerbalProperty.create(:herb_id => yellow_dock_root.id, :property_id => alterative.id, :specific => false)
HerbalProperty.create(:herb_id => yellow_dock_root.id, :property_id => laxative.id, :specific => false)
HerbalProperty.create(:herb_id => yellow_dock_root.id, :property_id => hepatic.id, :specific => false)
HerbalProperty.create(:herb_id => yellow_dock_root.id, :property_id => astringent.id, :specific => false)
HerbalPreparation.create(:herb_id => yellow_dock_root.id, :preparation_id => overnight_infusion.id, :favorite => false)
HerbalPreparation.create(:herb_id => yellow_dock_root.id, :preparation_id => decoction.id, :favorite => false)
HerbalPreparation.create(:herb_id => yellow_dock_root.id, :preparation_id => tincture.id, :favorite => false)
